services:
  - type: web
    name: meu-servidor-1
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: FRAME_ENC_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_WEB_USER
        sync: false
      - key: ADMIN_WEB_PASS
        sync: false
      - key: DEFAULT_API_PASS
        sync: false
